# Generated by Django 2.2.10 on 2020-04-07 21:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50, verbose_name='Name')),
                ('cust_number', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('Gender', models.CharField(choices=[('--', '--'), ('Male', 'Male'), ('Female', 'Female')], default='--', max_length=15, verbose_name='Gender')),
                ('address', models.CharField(max_length=200)),
                ('account_number', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_name', models.CharField(max_length=50, verbose_name='Expert Name')),
                ('expert_category', models.CharField(choices=[('salon expert', 'salon expert'), ('Appliance expert', 'Appliance expert'), ('Cleaning expert', 'Cleaning expert'), ('Fitness expert', 'Fitness expert'), ('General expert', 'General expert')], max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('Gender', models.CharField(choices=[('--', '--'), ('Male', 'Male'), ('Female', 'Female')], default='--', max_length=15, verbose_name='Gender')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(choices=[('salon service', 'salon service'), ('Appliance service', 'Appliance service'), ('Cleaning service', 'Cleaning service'), ('Fitness service', 'Fitness service'), ('General service', 'General service')], max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('location', models.CharField(choices=[('Salt lake city', 'Salt lake city'), ('Omaha', 'Omaha'), ('Chicago', 'Chicago'), ('Denver', 'Denver')], max_length=20)),
                ('appointment_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('cust_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app2.Customer')),
            ],
        ),
    ]
